export const UPDATE_MARKDOWN_TEXT = 'UPDATE_MARKDOWN_TEXT';
export const SET_PREVIEW = 'SET_PREVIEW';
export const UPDATE_EDITOR_VIEWCLASS = 'UPDATE_EDITOR_VIEWCLASS';
export const UPDATE_PREVIEW_VIEWCLASS = 'UPDATE_PREVIEW_VIEWCLASS';
export const UPDATE_EDITOR_HIDDEN = 'UPDATE_EDITOR_HIDDEN';
export const UPDATE_PREVIEW_HIDDEN = 'UPDATE_PREVIEW_HIDDEN';
export const UPDATE_ICON = 'UPDATE_ICON';